Add Outlook debug config and sideloading capability for Outlook and web
OfficeDev/Office-Addin-TaskPane pull request #100
Opened 2021-02-10 22:32 UTC by TCourtneyOwen

- Add debug configs for Outlook
- Update office-addin-debugging version to the one that supports outlook and web sideloading
- Add new "start:desktop:outlook" script
- Update convertToSingleHost to remove "start:desktop:outlook"

2021-02-11 11:31 UTC, igor-ribeiiro commented
The code looks fine to me, just have a look into the failing check case to understand what happened

2021-02-11 16:35 UTC, TCourtneyOwen commented
I need to update the tests to use the new method signature for startDebugging

2021-02-11 19:30 UTC, igor-ribeiiro approved these changes
Looks good for me!

2021-02-11 20:37 UTC, akrantz approved these changes
Looks OK overall. See comments.

2021-02-11 20:37 UTC, akrantz commented on convertToSingleHost.js
> +      || key === "start:desktop:outlook"
Why does this get deleted?

2021-02-11 20:37 UTC, akrantz commented on .vscode/launch.json
> +      "url": "https://localhost:3000/taskpane.html?_host_Info=Outlook$Win32$16.01$en-US$$$$0",
Did you ever update the vscode extension so the url could be optional?  Just asking, no change needed.

2021-02-11 20:48 UTC, akrantz commented on package.json
> +    "app-to-debug": "excel",
This is reverting some changes that were made on master.

2021-02-11 20:52 UTC, akrantz commented on package.json
> +    "document": ""
Why a blank document? Is this just so someone can see where to add it? Personally, I think we should leave "document" off and let them use the -d or --document parameter. We can document how to add this key to package.json to make it the default, but I don't think the empty value helps too much. 

Also, does this apply for both web and desktop sideload?  Have we really tested this out in practice? I think it really should have been two separate values that were more descriptive, e.g. "document_for_sideload_to_web" and "document_for_sideload_to_desktop".  Might need to chat more about this.

2021-02-11 20:52 UTC, akrantz commented on package.json
> +    "start:desktop:outlook": "office-addin-debugging start manifest.outlook.xml desktop --app outlook",
why are we doing this just for outlook? we didn't do it for other apps.

2021-02-11 20:53 UTC, akrantz commented on test/ui-test.ts
> +            await startDebugging(manifestPath, { appType:AppType.Desktop, app:toOfficeApp(host), devServerCommandLine:devServerCmd,
Please fix formatting. There should be a space after the colons.

2021-02-11 20:53 UTC, akrantz requested changes
See comments. (Sorry forgot to start a review first.)

2021-02-16 18:47 UTC, TCourtneyOwen commented on convertToSingleHost.js
> +      || key === "start:desktop:outlook"
We don't want this to remain in the yo office generated project - we just want the standard start:deskop one in the generated project which will work because manifest.outlook.xml will be renamed to manifest.xml.

2021-02-17 16:58 UTC, akrantz commented
@TCourtneyOwen What is the status with this pull request? Are you planning to address the comments?

2021-02-17 17:28 UTC, TCourtneyOwen commented on package.json
> +    "document": ""
We could leave it off - I am not adamant about including it.  You can include a desktop document too for sideloading but it will only work if that document already contains a webextension part.  Michelle documented sideloading to web and it tells how to use the "document" param in the context of a project. We could just leave this out of the template and people can add it if they want

2021-02-17 17:30 UTC, TCourtneyOwen commented on package.json
> +    "start:desktop:outlook": "office-addin-debugging start manifest.outlook.xml desktop --app outlook",
This script is only intended for internal use and will be stripped out during project generation.  The other hosts don't need it because they all use manifest.xml and can be invoked via the "start" script

2021-02-17 17:31 UTC, TCourtneyOwen commented
@akrantz I have been holding off on this PR until we can get the Outlook sideloading flight enabled for Prod - this is taking longer than I would like due to having to wait for PR approvals

2021-02-17 18:01 UTC, akrantz commented on package.json
> +    "app-to-debug": "excel",
@TCourtneyOwen Please fix this. Thanks. It needs to use underscores.

2021-02-17 18:01 UTC, akrantz commented on package.json
> +    "document": ""
Let's leave `document` off and let people add it if they want.

2021-02-17 18:03 UTC, akrantz commented on package.json
> +    "start:desktop:outlook": "office-addin-debugging start manifest.outlook.xml desktop --app outlook",
The script isn't for internal use, but is only needed when the template contains multiple hosts as outlook has a different manifest. When converted to a single host, manifest.outlook.xml is renamed to manifest.xml and then there isn't a need for a outlook-specific start command.

This is OK. I was just missing the context that manifest.outlook.xml gets renamed.

2021-02-17 18:08 UTC, akrantz commented
There are still outstanding comments that you could address. 

Even after the flight is enabled in Prod there may be some folks that don't have it and sideload won't work. Could we add a check to determine if Outlook can sideload and put an error message if not?

2021-02-17 18:12 UTC, akrantz requested changes
See comments.

2021-02-18 20:30 UTC, TCourtneyOwen commented on .vscode/launch.json
> +      "url": "https://localhost:3000/taskpane.html?_host_Info=Outlook$Win32$16.01$en-US$$$$0",
I did not

2021-02-18 20:30 UTC, TCourtneyOwen commented on package.json
> +    "document": ""
Removing "document" from template

2021-02-18 20:32 UTC, TCourtneyOwen commented on package.json
> +    "app-to-debug": "excel",
fixed locally

2021-02-18 20:37 UTC, TCourtneyOwen commented
Regarding this comment, are you suggesting a Office version check:

Even after the flight is enabled in Prod there may be some folks that don't have it and sideload won't work. Could we add a check to determine if Outlook can sideload and put an error message if not?

If so, I think we would need to add that to office-addin-dev-settings

2021-02-18 21:08 UTC, akrantz commented
Yes, I don't think the scripts can check whether the flight is enabled, but you could at least validate that the Office version has support for sideloading.

2021-02-19 18:47 UTC, TCourtneyOwen commented
I will see if I can find a way to determine the Outlook install version from the registry and we can add a check to office-addin-dev-settings.  I did complete the flight yesterday to roll out to Prod and verified that the feature works with a Prod version of Outlook, so that's cool

2021-02-19 18:48 UTC, akrantz commented
That's great. Thanks.

2021-02-19 18:57 UTC, TCourtneyOwen commented
I found the installed version for C2R installs under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration in the VersionToReport entry, but I am not sure if there is a similar key for MSI installs

2021-02-25 14:00 UTC, akrantz commented
@TCourtneyOwen Perhaps you should work to land this PR without the version check, and a separate PR can be done to add that. Perhaps Igor can work on it.

2021-02-25 14:01 UTC, akrantz approved these changes

2021-02-25 15:23 UTC, TCourtneyOwen commented
@akrantz I think that's a great idea and in fact I was thinking of asking Igor to do the version check as well.

@igor-ribeiiro I will create a work item for you to check the Outlook install version as part of the sideload command to determine if it's a valid version (needs to >= 16.0.13709.10000). We can check the installed version using our existing registry methods in Office-Addin-Scripts to check the ClientVersionToReport setting under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration

2021-02-25 16:53 UTC, merged