Updating office scripts packages versions
OfficeDev/Office-Addin-TaskPane pull request #101
Opened 2021-02-11 17:43 UTC by igor-ribeiiro

Updated all office adding scripts to their latest versions and fixed the functions necessary changes.

Tested with:
```npm run test```
And all tests gave the exact same results as before making these changes

2021-02-11 20:45 UTC, akrantz commented
@TCourtneyOwen Shouldn't we merge and publish this PR first?
https://github.com/OfficeDev/Office-Addin-Scripts/pull/382

2021-02-11 20:47 UTC, akrantz commented on test/ui-test.ts
> +            await startDebugging(manifestPath, {  appType:AppType.Desktop, app:toOfficeApp(host), devServerCommandLine:devServerCmd,
@igor-ribeiiro I'm not sure that you created your branch off of master. These changes look like they are from Courtney's changes. Let's chat offline and I can explain how to fix this.

2021-02-11 20:47 UTC, akrantz requested changes
See comments...

2021-02-11 20:50 UTC, TCourtneyOwen commented
Yes I agree we should merge and publish OfficeDev/Office-Addin-Scripts#382 but we need to see why the CI loop failed for that PR

2021-02-11 23:57 UTC, TCourtneyOwen commented
Latest versions of office-addin-scripts packages have been published so all the versions in package.json in this PR should be bumped up one for the patch version

2021-02-17 17:41 UTC, akrantz commented on test/ui-test.ts
> +            await startDebugging(manifestPath, {  appType:AppType.Desktop, app:toOfficeApp(host), devServerCommandLine:devServerCmd,
With the update of the office-addin-debugging package, the startDebugging() function changed. I pushed a commit which has the same changes but cleans up the formatting.

2021-02-17 17:59 UTC, igor-ribeiiro commented on test/ui-test.ts
> +            await startDebugging(manifestPath, {  appType:AppType.Desktop, app:toOfficeApp(host), devServerCommandLine:devServerCmd,
Just looked into the changes you committed and they look fine to me

2021-02-19 18:42 UTC, TCourtneyOwen commented
Why are there changes to so many other files in this PR if this was only intended to update packages? Was there perhaps a merge issue here from master?

2021-02-19 18:43 UTC, akrantz commented
I had started doing this in a previous PR, and along the way I found that there were lint errors and things to be fixed. I merged this into Igor's PR so he could finish it all.

2021-02-19 18:45 UTC, TCourtneyOwen approved these changes

2021-02-19 18:46 UTC, akrantz approved these changes

2021-02-19 18:47 UTC, akrantz commented
There was also the changes needed for startDebugging() breaking change.

2021-02-19 18:48 UTC, merged