Update webpack dev server v4
OfficeDev/Office-Addin-TaskPane pull request #130
Opened 2021-09-08 21:11 UTC by millerds

Fixes vulnerability

2021-09-08 22:44 UTC, igor-ribeiiro requested changes

2021-09-08 22:44 UTC, igor-ribeiiro commented on package.json
> +    "acorn": "^8.5.0",
When is this getting used?

2021-09-08 22:44 UTC, igor-ribeiiro commented on test/webpack.config.js
> +      https: env.WEBPACK_BUILD || options.https !== undefined ? options.https : await getHttpsOptions(),
Why can't we use the devCerts http function anymore?
Wouldn't it be better for us to update devCerts and import the updated one instead of simply getting rid of the function?

2021-09-08 22:51 UTC, akrantz commented on test/webpack.config.js
> +      https: env.WEBPACK_BUILD || options.https !== undefined ? options.https : await getHttpsOptions(),
It is being used. The getHttpsOptions() function is used to map the ca property to cacert since webpack changed the name of the https property. We don't want to change office-addin-dev-certs because this can be used with more than just webpack-dev-server or different versions of it and we don't want a breaking change or to create a different method.

2021-09-08 22:52 UTC, akrantz commented on package.json
> +    "acorn": "^8.5.0",
This is a nutty addition.   ;-)

2021-09-08 23:38 UTC, millerds commented on package.json
> +    "acorn": "^8.5.0",
:-) . . . That was the third commit in the list . . . it's a peer dependency of webpack and we are supposed to be installing peer dependencies.  It should have been added as part of the webpack v5 change, but it was missed and I didn't want to make a separate PR just for this one line.

2021-09-09 17:01 UTC, igor-ribeiiro approved these changes

2021-09-09 17:33 UTC, merged