Fix ie11 test
OfficeDev/Office-Addin-TaskPane pull request #148
Opened 2021-11-01 21:55 UTC by millerds

This should this git the test to compile such that the ie11 test can run correctly and be re-enabled.

2021-11-01 22:05 UTC, igor-ribeiiro approved these changes

2021-11-03 16:46 UTC, igor-ribeiiro reviewed
Where did you find these find process files?

2021-11-03 16:54 UTC, millerds commented
> Where did you find these find process files?

I looked at the code from the find-process package in github and took the portion of them that matched what we needed.  I wanted to narrow it down even more, but that would risk breaking the code that is verified working and would take more time.

2021-11-03 16:56 UTC, millerds commented on tsconfig.json
> +    "esModuleInterop": true,
Directly for this fix no . . . it does make us more bullet proof for future changes that need to be compatibly with IE webview, but it's not needed for this change directly now that I've added the find code locally (it was part of the first change the turned out not to work).

2021-11-03 16:57 UTC, igor-ribeiiro commented
> > Where did you find these find process files?
> 
> I looked at the code from the find-process package in github and took the portion of them that matched what we needed. I wanted to narrow it down even more, but that would risk breaking the code that is verified working and would take more time.

Why isn't the node find-process package working?

2021-11-03 17:03 UTC, millerds commented
> > > Where did you find these find process files?
> > 
> > 
> > I looked at the code from the find-process package in github and took the portion of them that matched what we needed. I wanted to narrow it down even more, but that would risk breaking the code that is verified working and would take more time.
> 
> Why isn't the node find-process package working?

I wasn't able to find out specifically why, but it's the use of this library that cause the test in IE webview to stop working . . . the test taskpane fails to load because of a javascript error (I was unable to figure out what specific error).  It's related to trying to compile for down level es5 standard (which we've setup in the compilation process for the taskpane projects).

2021-11-03 17:05 UTC, igor-ribeiiro commented
But if you simply copied the code from npm and put it locally, what changed that would make the local code work?

2021-11-03 17:08 UTC, millerds commented
It's compiled from our local code rather then just importing the package.  I also tweaked how the main module is defined.  It works for the IE 11 web view (still trying to confirm mac doesn't break).

2021-11-03 17:50 UTC, akrantz requested changes
I don't think it's a good idea to write this code in this way. It's not abstracted, organized, readable, or very maintainable. Please see other comments.

2021-11-03 17:50 UTC, akrantz commented on test/end-to-end/src/find-process-by-name.ts
> +const utils = require("./find-process-utils");
You should use `import` and not `require()` with TypeScript.

2021-11-03 17:50 UTC, akrantz commented on test/end-to-end/src/find-process-by-name.ts
> +function matchName(text, name) {
What is all this code doing? I find this hard to read and understand.

2021-11-03 17:50 UTC, akrantz commented on test/end-to-end/src/find-process-by-name.ts
> +  const platform = process.platform;
Should there be separate functions for each platform? If you're writing your own code to find the process id given a process name, shouldn't this be done separately outside the test code itself? Was this an imported package that we stopped using? Why not have functionality from office-addin-debugging which already has some process stuff in pace?

2021-11-03 20:59 UTC, millerds commented
Managed to find a kill by process name command for the command line I can trigger on the mac.  Much simpler and more direct.

2021-11-03 21:01 UTC, igor-ribeiiro approved these changes

2021-11-03 23:09 UTC, millerds commented
Discussed offline.

2021-11-03 23:09 UTC, merged