Json template
OfficeDev/Office-Addin-TaskPane pull request #157
Opened 2022-03-08 23:08 UTC by igor-ribeiiro

Creating the code for what would be the JSON templates. Merging into a different branch other than master to not break existing code.

2022-03-08 23:30 UTC, igor-ribeiiro commented
> Were you going to remove the WXP specific tests too (I mean as part of the branch)? They test shouldn't pass if they are still part of the test suite.

Yeah, just did, had forgotten previously

2022-03-08 23:32 UTC, igor-ribeiiro commented on manifest.json
> +{
I don't think this `.json` is enough yet. But I wanted to have something there before we commit to creating a functional one
So this is more of a placeholder `.json` manifest for now

2022-03-09 19:13 UTC, millerds requested changes
So you're not planning on making even a unit test for the template?

2022-03-09 19:13 UTC, millerds commented on manifest.json
> +{
So are you planning on a further change to this repo to fill it out?  Is there a separate work item for that or is this part of the same work item (that won't be closed until it's done)?

2022-03-09 19:13 UTC, millerds commented on package.json
> +    "test": "",
If you look at other places we don't have tests (see scripts repo) then we use an "Echo" message indicating so.

2022-03-09 19:40 UTC, igor-ribeiiro commented
> So you're not planning on making even a unit test for the template?

What would the unit test be about? Those templates in general had unit and UI tests for WXP but no tests at all for Outlook.
So given this would be focused on outlook, I just removed the WXP tests

2022-03-09 19:42 UTC, igor-ribeiiro commented
There is another work item for creating the valid json manifest:
"Create and test valid json manifest"
I like already pushing these changes as we won't depend on having the valid json in order to do the Yo Office work.

2022-03-09 21:41 UTC, millerds approved these changes

2022-03-09 23:12 UTC, merged