Add PR template file
OfficeDev/Office-Addin-TaskPane pull request #169
Opened 2022-05-06 18:36 UTC by millerds

This will give us some beginning description text for any PR that will encourage including specific people on the review if there are specific types of changes

2022-05-06 18:50 UTC, igor-ribeiiro requested changes
Would be nice to add a section asking how the person tested their changes.

2022-05-09 17:14 UTC, millerds commented
/Azurepipelines run

2022-05-09 19:58 UTC, Rick-Kirkham approved these changes

2022-05-09 21:31 UTC, igor-ribeiiro approved these changes

2022-05-09 21:33 UTC, merged