Add postinstall .Net check
OfficeDev/Office-Addin-TaskPane pull request #170
Opened 2022-05-06 19:26 UTC by millerds

This will indicate weather or not .Net is installed (needed by the template) at the end of running 'npm install'

2022-05-06 20:05 UTC, akrantz commented
Shouldn't this be provided from office-addin-scripts instead of directly in office-addin-taskpane?

2022-05-06 20:39 UTC, igor-ribeiiro requested changes

2022-05-06 20:39 UTC, igor-ribeiiro commented on checkDotNet.js
> +  console.log(chalk.bold.red(".Net 5 or greater is required for json manifests."));
Given that we are catching this error and letting the process continue, I think this message should also include something telling the customer to install `.net` 5.
Like:
`Please install the latest .net 5 or greater`

2022-05-06 20:40 UTC, igor-ribeiiro commented
> Shouldn't this be provided from office-addin-scripts instead of directly in office-addin-taskpane?

It is also in the scripts when going to sideload.
We have thought that having in both places could warn customer quicker about this requirement

2022-05-06 20:42 UTC, akrantz commented
It's going to be a nightmare to maintain in the project itself and merge across. You're better off having it only in the office-addin-scripts package.

2022-05-06 20:46 UTC, akrantz commented
You should just have whatever command is needed to run give an error if .NET isn't installed when it needs to be. This should not be done in the project itself.

2022-05-06 22:07 UTC, millerds commented
This is specific to the json manifest template and only an intermediate step for build.  

.Net will be needed when a developer tries to sideload the json manifest project.  I've already added the check to sideloading in office-addin-dev-settings (behind the scenes) to say .Net needs to be installed.  Louis was suggesting that we need to advise devs sooner that this is a requirement and not depend on documentation.  I thought about exporting the method in office-addin-dev-settings and using it, but we will be taking this back out in just a couple more months (when more work in outlook and the new MetaOS service are done) and I wondered if we wouldn't run into some longer-term maintenance costs if it were publicly supported in the scripts package.  The risk is probably small and if we were intending to support this longer term I would definitely do it via the scripts package.  This seems like it would be easier to remove later on.

2022-05-06 22:09 UTC, akrantz commented
If the check is in office-addin-dev-settings, I don't see why it needs to be here.

2022-05-06 22:14 UTC, millerds commented
> If the check is in office-addin-dev-settings, I don't see why it needs to be here.

Personally I could go either way (both or just sideload) . . . the point brought up comes down to user experience.  They create a new project, npm install, but then when they do npm start there a new error saying they need .Net 5 runtime and we aren't installing it for them (too complicated to do via node/java).  Is that too annoying for developers not to have the message earlier that they need an extra manual install?

2022-05-06 22:16 UTC, akrantz commented
Sure, but the javascript code to detect .NET is missing is already in office-addin-dev-settings. Why go and add script in the project itself as well? It's simpler and better to have the checks where needed.

2022-05-06 22:23 UTC, akrantz commented
You could still make the postinstall step run a command in office-addin-scripts to achieve the same thing.

postinstall: office-addin-dev-settings check-dotnet-installed

2022-05-06 23:20 UTC, millerds commented
It boils down to 3 options:

1. Only have the check in sideload. 
Pro: only one place in code to deal with at the point it's needed.  
Con: developers aren't notified of the dependency until later in the loop
2. Check in sideload and separately check on package install.  
Pro: developers notified sooner of the dependency and no public method.  
Con: similar code in two places
3. Check in sideload and call check on package install. 
Pro: developers notified sooner and code is shared.  
Con: Potential for new dependency on method that will be deleted in a short time.

It's a tradeoff no matter which way we go.

2022-05-07 02:42 UTC, akrantz commented
No, you can have the code only in the package, but still provide the check in multiple places. Nothing here requires the code to go in the project itself.

2022-05-07 02:45 UTC, akrantz commented
I think this is your step 3, but I don't see what the con is. There has been and will continue to be a dependency on office-addin-dev-settings regardless of whether or not this check is done. If you're saying it needs to be a direct dependency on office-addin-debugging, then I would say export the functionality from there so that package can be called.

2022-05-09 16:42 UTC, millerds commented
> I think this is your step 3, but I don't see what the con is. There has been and will continue to be a dependency on office-addin-dev-settings regardless of whether or not this check is done. If you're saying it needs to be a direct dependency on office-addin-debugging, then I would say export the functionality from there so that package can be called.

The Con for option 3 is that in order to use it method in the project it has to be exported from the package.  This would also make it available for anyone to import our package and use in their own project in their own way.  We would then take it away just a couple months later.  This is a small window, but still a possibility.

2022-05-09 16:58 UTC, millerds commented
I occurs to me that another con is potentially breaking projects generated with 'yo office' when we remove the method.  Developers who update the their packages after we remove the backward conversion would still have the postinsall script pointing to it that would need to be cleaned up by them.  If the check is local the project would continue to work after we remove it, it would just be checking for .Net when it didn't need to anymore.

2022-05-09 17:03 UTC, akrantz commented
There is not a big cost to add it to the package, nor remove it later. The cost is how you manage the script and changes to it and merge it across the templates, and then when you remove it, customers which have a certain version have to remove it manually rather than having the package updated to say this is no longer supported and tells them to remove the script line.

2022-05-09 20:08 UTC, millerds commented
This is only ever going to be provided to our json manifest template and not merged to the others.  We haven't finalized plans for json manifest templates (how many, how are they managed, etc), but this will be removed before we have multiple json manifest based templates.

2022-05-20 18:36 UTC, closed without merging