TS templates for WXP Toolkit
OfficeDev/Office-Addin-TaskPane pull request #220
Opened 2023-11-23 04:54 UTC by YueLi-MSFT

Thank you for your pull request!  Please provide the following information.

---

**Change Description**:

    Describe what the PR is about. 

1. **Do these changes impact any *npm scripts* commands (in package.json)?** (e.g., running 'npm run start')
    If Yes, briefly describe what is impacted.

2. **Do these changes impact *VS Code debugging* options (launch.json)?**
    If Yes, briefly describe what is impacted.

3. **Do these changes impact *template output*?** (e.g., add/remove file, update file location, update file contents)
    If Yes, briefly describe what is impacted.

4. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    If Yes, briefly describe what is impacted.

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:

    Describe manual testing done.

2023-11-27 20:18 UTC, millerds requested changes
Note that the current json manifest branches were reduced from the master branch to target Outlook because that is all that was supported at the time.  When changing it back to support other host we should continue to follow the patterns used in general and if there is a desire to change the patterns then a task/bug should logged and discussed as a change for all templates.

We should be following the branch progression for changes . . . meaning changes for json manifest template goes to "json-preview" branch first.  Changes being made ready for public consumption should then be merged from "json-preview" to "json-preview-yo-office-prerelease" and verified using 'yo office' there before finally being pushed to "json-preview-yo-office" for customers to use.

On top of following the branch progression, we need to coordinate with the documentation team (Ricky) and managing the branches and Outlook template (which is going to GA in a couple of months) as they own the repo management now.

2023-11-27 20:18 UTC, millerds commented on .vscode/launch.json
> +    {
Should probably order the configs in the same ways as is done in the master branch to maintain uniformity.

2023-11-27 20:18 UTC, millerds commented on package.json
> -    "app_to_debug": "outlook",
This should not be removed for this special case.  If it doesn't look like it's needed then we should log a bug to remove it in general across all the templates.

2023-11-28 06:44 UTC, QuanfuXiao commented on package.json
> +    "start:outlook": "office-addin-debugging start manifest.json --app outlook",
Thanks Darren, it is reasonable to leave one command in "package.json" and pass parameters in tasks config.

2023-11-28 06:46 UTC, QuanfuXiao commented on .vscode/launch.json
> +    {
@millerds , should we use unique port for each config?

2023-11-28 17:44 UTC, millerds commented on .vscode/launch.json
> +    {
No . . . the ports listed are the standard cases for attaching to the launched webview host.  The chrome version and the legacy version each have that as their default.

I'm just asking that the order of each config match that of the master branch.

2023-11-28 17:45 UTC, millerds commented on package.json
> +    "start:outlook": "office-addin-debugging start manifest.json --app outlook",
That is what the master branch does . . . use that as your starting point.

2023-11-29 02:27 UTC, YueLi-MSFT commented on .vscode/tasks.json
> +    {
Thanks Millerds! Will do!

2023-11-29 17:26 UTC, millerds commented on .vscode/tasks.json
> +      "command": "npm link office-addin-dev-settings --force",
I don't think we want to do this automatically as part running in VS Code.  This should be left for someone to use if they explicitly want to try a change to the scripts package locally.

2023-11-29 17:41 UTC, QuanfuXiao commented on .vscode/tasks.json
> +      "command": "npm link office-addin-dev-settings --force",
Yeah, it is only for POC demo and will be deleted when TAOS sideload for WXP manifest is ready.

2023-11-29 17:49 UTC, QuanfuXiao commented
Hi @millerds , regarding the branch issue, is it reasonable to add a new branch only for the toolkit? Since "json-preview-yo-office" should remain to be used in Yo Office for Outlook only.

2023-11-29 17:53 UTC, millerds commented
> Hi @millerds , regarding the branch issue, is it reasonable to add a new branch only for the toolkit? Since "json-preview-yo-office" should remain to be used in Yo Office for Outlook only.

This is something that needs to be discussed with the docs team that jointly owns maintaining the templates.  I plan on figuring that out and we'll have to have a plan in place before modifying the existing branches.

2023-11-30 03:07 UTC, YueLi-MSFT commented on .vscode/launch.json
> +    {
Got it. Thanks @millerds

2023-12-01 17:41 UTC, millerds commented on .vscode/tasks.json
> +      "type": "shell",
why is this needed.

2023-12-01 17:44 UTC, millerds commented on manifest.json
> +                      "label": "Hello Excel",
We should not be labeling this specific to one host.  This is used by all the hosts.

2023-12-01 17:48 UTC, millerds commented on src/commands/commands.ts
> +async function action(event: Office.AddinCommands.Event) {
This template is used for Outlook too.  If you want to make a command sample for different hosts (something not done in current xml based templates) then you need to make the template handle all hosts, or make options for host specific stuff that is cleaned up by the convert script when instantiating template for a particular host.

2023-12-04 05:45 UTC, QuanfuXiao commented on .vscode/tasks.json
> +      "type": "shell",
Will change it back. We added a "npm link" script for demo, but it seems not work well with "npm install" ("npm link" will modify files in node-modules, but "file been used" issue often occur when executed after "npm install" task).  This change still cannot solve all the issue.

2023-12-04 05:47 UTC, QuanfuXiao commented on src/commands/commands.ts
> +async function action(event: Office.AddinCommands.Event) {
Yeah, we will add commands of all hosts later.

2023-12-12 09:33 UTC, YueLi-MSFT commented on src/taskpane/taskpane.ts
> +    document.getElementById("run").onclick = runPowerPoint;
Yes, we hope that the template can support WXPO apps for Teams Toolkit feature.

2024-01-15 07:21 UTC, closed without merging