Draft PR: default-ts template for WXP on Toolkit
OfficeDev/Office-Addin-TaskPane pull request #230
Opened 2024-01-15 07:29 UTC by YueLi-MSFT

Thank you for your pull request!  Please provide the following information.

---

**Change Description**:

    Describe what the PR is about. 

1. **Do these changes impact any *npm scripts* commands (in package.json)?** (e.g., running 'npm run start')
    If Yes, briefly describe what is impacted.

2. **Do these changes impact *VS Code debugging* options (launch.json)?**
    If Yes, briefly describe what is impacted.

3. **Do these changes impact *template output*?** (e.g., add/remove file, update file location, update file contents)
    If Yes, briefly describe what is impacted.

4. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    If Yes, briefly describe what is impacted.

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:

    Describe manual testing done.

2024-01-16 19:07 UTC, millerds requested changes
I think we still have too many special cases here and part of that comes from trying to generate a multi host project from a script and project template that was designed for a single host.  There should be a better way handle that that doesn't require extra special handling.  

This simplest thing I can think of would be to have a host option "WXPO" that could be considered when cleaning up the project.  Some thought would need to be made to see how well that would work (possibly even for xml manifests).

A more challenging solution that would require more though and changes might be to make the "host" argument to the script an array (or string to maintain compatibility) so that a set of host could be passed and then the project could be more combinatorial.  This would create some complications around getting the manifest and webpack file to match.  In the end, more work, but potentially an more featureful result.

2024-01-17 07:11 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +} else if (manifestType === "json" && projectName === "TeamsFx") {
Okay, I will remove the check for "projectName"

2024-01-17 09:26 UTC, YueLi-MSFT commented
> I think we still have too many special cases here and part of that comes from trying to generate a multi host project from a script and project template that was designed for a single host. There should be a better way handle that that doesn't require extra special handling.
> 
> This simplest thing I can think of would be to have a host option "WXPO" that could be considered when cleaning up the project. Some thought would need to be made to see how well that would work (possibly even for xml manifests).
> 
> A more challenging solution that would require more though and changes might be to make the "host" argument to the script an array (or string to maintain compatibility) so that a set of host could be passed and then the project could be more combinatorial. This would create some complications around getting the manifest and webpack file to match. In the end, more work, but potentially an more featureful result.

Yes, you're right! I will refactor the changes based on these comments. I will push a new iteration as soon as possible. Thanks Darren!

2024-01-19 17:27 UTC, millerds requested changes

2024-01-19 17:27 UTC, millerds commented on convertToSingleHost.js
> +async function updatePackageJsonForMultiHostsWXPO(host) {
This looks like a duplicate of updatePackageJsonForSingleHost (with better formatting) . . . we should be using one method . . . not two.

2024-01-19 17:27 UTC, millerds commented on convertToSingleHost.js
> +} else if (host === "wxpo" && manifestType === "json") {
We should be merging the project modification and not creating special case for a single projec type.

2024-01-19 17:27 UTC, millerds commented on convertToSingleHost.js
> +if (host !== "wxpo" || manifestType !== "json") {
So is the idea that the only json manifest project option is one that includes everything in it? I'm not sure that is the way we want to go here. We should continue to allow single host projects with json manifests.

2024-01-19 17:27 UTC, millerds commented on convertToSingleHost.js
> +async function convertProjectToMultiHostsWXPO(host) {
We should be able to use one method to these common tasks (though it may have to be renamed to be more representative of the operation).

2024-01-19 17:27 UTC, millerds commented on convertToSingleHost.js
> +modifyProjectForMultiHostsWXPO(host).catch((err) => {
I don't understand why this is being called after doing all the other modification work.

2024-01-19 17:27 UTC, millerds commented on convertToSingleHost.js
> +  wxpoHosts.forEach(async function (wxpoHost) {
If I understand this loop correctly, we're repeatedly modifying the xml manifest file and the core taskpane.ts file . . . which we shouldn't be doing.

2024-01-22 07:26 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  if (manifestType === "json") {
It doesn't need this anymore. I deleted it.

2024-01-22 08:32 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +async function modifyProjectForJSONManifestWXPO() {
Okay, maybe this change can put in this method `modifyProjectForJSONManifest`, instead of adding new functions for it. Am I right about that?

2024-01-22 08:36 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +if (host !== "wxpo" || manifestType !== "json") {
Yes, if the branch(json-wxpo-preview) is only for toolkit to use, then the json manifest supports wxpo hosts at the same time, and doesn't give the developer the option to choose hosts. I understand that you want the json manifest to support a single host, right?

2024-01-22 08:37 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  if (typeof manifestType == "undefined" || manifestType != "json") {
Okay, I removed it.

2024-01-22 08:38 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  await unlinkFileAsync("webpack.config.js");
It was not needed it. Removed.

2024-01-22 08:39 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  hosts = ["outlook", "excel", "word", "powerpoint"];
Okay, removed.

2024-01-22 09:10 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +async function updateCommandsFileForJSONManifestWXPO() {
Okay, I will add commands.{host}.ts for it.

2024-01-22 09:29 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  if (typeof manifestType !== "undefined" && manifestType == "json") {
Yes, I have removed it.

2024-01-22 09:30 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +    const debugScripts = {
Okay, I will change it.

2024-01-22 09:48 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +async function updateSrcFolderForJSONManifestWXPO() {
Yes, I agree with you. But the way you said this may not apply to the current case. Because If I don't generate it by this script, there's no way to guarantee that the source code is exactly right, and the developers will see the file `taskpane.ts`with multiple `Office.onReady() `, which is not right. So, do you have any better practice about here?

2024-01-22 18:48 UTC, millerds commented on convertToSingleHost.js
> +if (host !== "wxpo" || manifestType !== "json") {
I've mentioned elsewhere that this and the other repos that support office add-ins are not just for teams, but will continue to support projects generated using 'yo office' and that includes projects that are just for a single host.  Being able to generate a project that support multiple hosts is a great improvement, but it is not a replacement for the existing single host behavior.  We should be able to support a single or multiple cases.

I thought I saw in the spec for WXP in with json manifests that there were single host options in the toolkit . . . but maybe I'm remembering incorrectly?

Also note that the branch is temporary for preview development.  The goal should be to merge that into master once WXP in json manifest support ships and not have to maintain a separate branch for it.

2024-01-22 19:10 UTC, millerds commented on convertToSingleHost.js
> +async function updateSrcFolderForJSONManifestWXPO() {
There are a couple ways I can think of to solve this.  

First, if you are adding a "wxpo" case, then you just need a ts file that is exactly what you want to output for wxpo, and the convert script replaces "taskpane.ts" with that file (like it would for the single host).  That file would need just one onReady definition that has an if block for which host is loading it and then associate the right run method to match.  The run methods would be defined in the same file.

Another option (slightly better in my opinion) is to have taskpane.ts have a universal "onReady" function that checks the host and makes the right association of the run method and then just the run method is defined each of the ${host}.ts files.  Thost host specific files are then imported into taskpane.ts in include the code that is there (this is similar to the state of the repo before conversion).  The convert script would then clean up any host files that are not part of the target host and could remove those parts of the if clause in the taskpane.ts file.

2024-01-24 07:59 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  delete content.config["app_to_debug"];
@millerds Hi Darren, I understand your concern. As I understand it, in this case, whether it's run scripts or tasks, will pass the `app `param to office-addin-* modules and don't need to read `app_to_debug`. 
https://github.com/OfficeDev/Office-Addin-Scripts/blob/67750235b86b7ebc5fd0408eada6e8feba81a81a/packages/office-addin-debugging/src/commands.ts#L54

2024-01-24 08:07 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  const checkOSTask = {
Okay.

2024-01-25 03:01 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +async function updateSrcFolderForJSONManifestWXPO() {
Thanks @millerds for your advice! I made `wxpo` a separate host so that I wouldn't have to target `wxpo` with a lot of specific logics, and it wouldn't be any different from any other host.

2024-01-25 14:43 UTC, akrantz commented on .vscode/tasks.json
> +        "Install"
Does this cause Install task to run every time debugging is started? That's not desirable if it is. Certainly npm install needs to be run first, for the project but not every time.

2024-01-25 14:46 UTC, akrantz commented on convertToSingleHost.js
> +async function convertProjectToSingleHostForXMLManifest(host) {
There is a lot of commonality between the two functions. Would it be better to pass in the manifest type, and just have one function which can call out where differences are needed based on the manifest type? That way you don't have to ensure the common code logic stays in sync between both functions.

2024-01-25 14:49 UTC, akrantz commented on .vscode/tasks.json
> +        "Check OS",
I don't see a "Check OS" task. The repository should be usable fully without running convertToSingleHost.js script.

What is the purpose of "Check OS"?

Like my comment about Install, does this need to be run every time debugging is launched? Usually start debugging shows an error if it cannot be done.

2024-01-25 14:50 UTC, akrantz commented on .vscode/tasks.json
> +        "Check OS",
Also, the tasks are in alphabetical order, and would be nice to keep it that way. So please put "Check OS" in the appropriate place.

2024-01-25 14:52 UTC, akrantz commented
I'm not crazy about the wxpo host or the fact that there are wxpo manifest files being added. Really the project already supports all hosts, and I wanted to have yo office be able to keep it that way, but that's not how it's done so yo office runs convertToSingleHost.js script.  I can see calling convertToSingleHost for "wxpo" in terms of removing other hosts, but I would rather see the full manifest file modified to remove the undesirable hosts rather than add another wxpo manifest file which has to be maintained as well.

2024-01-25 14:55 UTC, akrantz commented on src/taskpane/wxpo.ts
> +Office.onReady((info) => {
I don't think you should have this file. This was set up already so relevant code is in taskpane.ts. Or there should be separate word.ts, excel.ts, etc. files which can each check if info.host is for their host and only do something for that host.

2024-01-25 18:46 UTC, millerds commented on .vscode/tasks.json
> +        "Install"
This is something that was added for toolkit integration in the json-preview branch.  The toolkit (which is where the focus seems to be) does not do 'npm install' as part of project generation like 'yo office' does . . . they include it in the debug configuration like this.  It means for the toolkit the first time you run the debugger it takes much longer to get going (as opposed to the project generation taking longer), but that is the design they insist on.

The side effect for 'yo office' by having this is that triggering the debugger takes a little more time because 'npm install' runs and confirms everting is installed from when the project was generated.

I would agree that it's better to do it as part of project generation, but that is something the toolkit would have to change.

2024-01-25 18:59 UTC, millerds commented on convertToSingleHost.js
> +async function convertProjectToSingleHostForXMLManifest(host) {
Agreed

2024-01-25 21:13 UTC, millerds requested changes
I'm not sure about having all those empty files.

2024-01-25 21:13 UTC, millerds commented on src/taskpane/wxpo.ts
> +Office.onReady((info) => {
I believe the concern was in the case of WXPO which supports multiple hosts that there would be multiple "onReady" method defined . . . one for each host.  This was one of two suggestions I had made previously.  It's the easier one where it's just another "host" option even though it's really a combination of the others.

The other suggestion I had made was having a single shared file for the onReady method with the code for the methods being imported from the other ts files which are imported.  The convert script is then updated to delete the appropriate files and modify the shared file accordingly based on the host selected (with wxpo leaving them).

Of course, having multiple onReady methods doesn't hurt either as the add-ins framework was designed to allow that.  Keeping each host's code in a separate file seems like better organization even if there are multiple onReady methods.

2024-01-25 21:13 UTC, millerds commented on src/taskpane/wxpo.ts
> +    document.getElementById("run").onclick = runOutlook;
If we do have reason to keep using this one file then you should doe these first two line outside of the if blocks since it's the same for all hosts.  The only difference between them is picking which run method to wire up.

2024-01-29 06:11 UTC, YueLi-MSFT commented on convertToSingleHost.js
> -}
Not moved, just change the position.

2024-01-29 06:16 UTC, YueLi-MSFT commented on src/taskpane/wxpo.ts
> +    document.getElementById("run").onclick = runOutlook;
Yes, you're right! I will change it. Thanks Darren!

2024-01-29 06:52 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +const jsonHosts = ["excel", "outlook", "powerpoint", "word", "wxpo"];
Okay, I will change it.

2024-01-29 07:47 UTC, YueLi-MSFT commented on .vscode/tasks.json
> +        "Check OS",
Hi Darren, once the manifest schema for WXP is locked down, we will change the code in `office-addin-scripts` to make WXP and outlook consistent, and also sideload from Taos service. So WXP need to Check OS too.

2024-01-29 07:49 UTC, YueLi-MSFT commented on .vscode/tasks.json
> +        "Install"
Okay, I will change it in `convertToSingleHost.ts`. Thanks!

2024-01-29 07:52 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +async function deleteFoldersAndSupportFiles() {
Okay.

2024-01-29 07:53 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  }
Okay, you're right! I really hadn't thought about cli before. Will add it.

2024-01-29 08:13 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +      task.script = taskScripts[task.label];
There is `start:desktop -- -- app host` in the tasks.json file, I wiil remove `desktop` for all hosts. And in the method `updatePackageJsonForJSONManifest`, scripts contain `"start:"` are deleted.

2024-02-01 17:46 UTC, millerds requested changes
This looks much closer to what I was anticipating would be needed.  There are a few specific comments still and the open question of organization of the code for multiple hosts (Adams comment about reusing the separate host taskpane files instead of making a separate one that has the same code).  On top of that I noticed some things that could make the script better in general (i.e. general improvements on the current script) . . .

In looking at this now the 2 updatePackageJsonFor*Manifest methods should be collapsed into the core updatePackageJoson method.  For the work that they do this means:
- Don't delete the signin and signout scripts.  Really this should done already since we now have to deploy using the authenticated service for xml as well as json.
- The special start scripts can stay for both, but I personally think they are unecessary . . .  The are basically doing the same thing as the start script, but with some extra parameters and could be removed from the base package.json file.
- The update to content.scripts.test can be made for both cases insted of just one.
- The core package.json could be passed the manifest type and then just to the 'start', 'stop', and 'validate' change all the time.  Technically this is unnecessary for the xml case since that is currently the default, but it removes the need for the special case and if the default case changed in package.json then the convert script wouldn't need to be updated to match.

The CheckOS injection needs to be removed from the script.  It doesn't make sense now that it's conditional on the host type that is being debugged.

2024-02-01 17:46 UTC, millerds commented on convertToSingleHost.js
> +  }
Actually . . . this is already taken care of in another part of the script which you have kept.  This isn't needed here and removes the need for the host argument.

2024-02-01 17:46 UTC, millerds commented on convertToSingleHost.js
> +      task.script = taskScripts[task.label];
I see now . . . this is a bug in the existing script which removes the 'start:' commands but doesn't update the task.json file.  A couple of comments about this:

A simpler update to the file would be to just replace the "start:desktop" with "start" (possibly doing an operation on the raw string before it's parsed into json).

We could also update other part of the script to not delete the 'start:desktop' script case so this still worked.  This is probably the better case since it was only doing that because only Outlook was supported (no need to support the others).

A third option would be to edit the original task.json and package.json to remove the "start:desktop" case in general.  That is essentially what "start" does anyway since "desktop" is the default mode anyway.

Personally I like the 3rd option.

2024-02-01 17:46 UTC, millerds commented on convertToSingleHost.js
> -}
Same thing.  Question still remains . . . why?

2024-02-02 02:56 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  if (manifestType === "json") {
Okay. But have a stupid question here:
Will that parameter `manifestType` be passed on Yo office side?

2024-02-02 03:00 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +    // Specify a host for json manifest
Sounds good！

2024-02-02 03:01 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  }
You're right! I will delete it.

2024-02-02 03:16 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +      task.script = taskScripts[task.label];
Yes. The third option makes more sense. I will remove the "start:desktop" in the tasks.json and package.json files.

2024-02-02 06:36 UTC, YueLi-MSFT commented on convertToSingleHost.js
> -}
Sorry, I finally understand what you mean. The method `updateWebpackConfigForJSONManifest` user in the method `modifyProjectForJSONManifest`, just put this method `updateWebpackConfigForJSONManifest` with the other methods in this method `modifyProjectForJSONManifest`. :)

2024-02-02 17:21 UTC, millerds commented on convertToSingleHost.js
> +  if (manifestType === "json") {
Yes . . . that it the point of the changes made to this file recently.  The same repo will house the xml and json template and the call to generate the project will pass the type parameter to script (thus 'const manifestType = process.argv[3];').  I have a change for generator-office plugin to do this, but I gave to get some changes replicated to all the template repos before that change is checked in.  Currently we are in the process of doing that.

2024-02-04 05:35 UTC, YueLi-MSFT commented
> This looks much closer to what I was anticipating would be needed. There are a few specific comments still and the open question of organization of the code for multiple hosts (Adams comment about reusing the separate host taskpane files instead of making a separate one that has the same code). On top of that I noticed some things that could make the script better in general (i.e. general improvements on the current script) . . .
> 
> In looking at this now the 2 updatePackageJsonFor*Manifest methods should be collapsed into the core updatePackageJoson method. For the work that they do this means:
> 
> * Don't delete the signin and signout scripts.  Really this should done already since we now have to deploy using the authenticated service for xml as well as json.
> * The special start scripts can stay for both, but I personally think they are unecessary . . .  The are basically doing the same thing as the start script, but with some extra parameters and could be removed from the base package.json file.
> * The update to content.scripts.test can be made for both cases insted of just one.
> * The core package.json could be passed the manifest type and then just to the 'start', 'stop', and 'validate' change all the time.  Technically this is unnecessary for the xml case since that is currently the default, but it removes the need for the special case and if the default case changed in package.json then the convert script wouldn't need to be updated to match.
> 
> The CheckOS injection needs to be removed from the script. It doesn't make sense now that it's conditional on the host type that is being debugged.

Thank Darren! I will recode the logic about Adams's comment. And I will change the 2 methods `updatePackageJsonFor*Manifest `to collapse into the core `updatePackageJoson` method.

2024-02-07 18:50 UTC, millerds requested changes

2024-02-07 18:50 UTC, millerds commented on convertToSingleHost.js
> +  let manifestContent;
nit: Why does this have to be defined outside of the 'if'?  Do so suggests it's used elsewhere.

2024-02-07 18:50 UTC, millerds commented on convertToSingleHost.js
> +    hosts.forEach(async function (host) {
This doesn't make sense to me . . . if I read correctly, you are overwriting the same 'taskpane.ts' file with different host files over and over again.

2024-02-07 18:50 UTC, millerds commented on convertToSingleHost.js
> +  if (manifestType === "json" && host === "wxpo") {
As mentioned in discussion, the code shouldn't depend on the manifest type, it should just depend on the host.  

A wxpo host can mean keep the wxpo host ts files and the taskpane.ts file can import those files specifically and the others can be removed.  An individual host designation can overwrite the taskpane.ts file per current implementation.

This could be further generalized using an array of hosts asked for (where wxpo gets expanded to ["word", "excel", "powerpoint", "outlook"] and individual host to ["host"}), iterating through the list of supported host and deleting the ts files in the supported list that aren't in the asked for list.

2024-02-07 18:50 UTC, millerds commented on convertToSingleHost.js
> +  // Remove special start scripts
This shouldn't be needed anymore if you updated package.json to no have them in the first place.

2024-02-20 06:59 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  if (manifestType === "json" && host === "wxpo") {
Yes, I have removed the check for manifestType. There is only dependent on the host check. Thanks Darren!

2024-02-20 18:04 UTC, millerds requested changes

2024-02-21 02:35 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +    if (host === "onenote" || host === "project") {
Yes, you're right! Thanks Darren!

2024-02-21 06:39 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +function capitalizeFirstLetter(string) {
I will remove it because it is useless now.

2024-02-21 06:54 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +    for (const file of files) {
Okay. This is a really good solution. Thanks Darren!

2024-02-21 06:57 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +        await appendFileAsync(`./src/taskpane/taskpane.ts`, taskpaneContent);
Wow! You make a good point. I will change it. Thanks Darren!

2024-02-22 20:24 UTC, millerds requested changes
I think your code in convertProjectToSingleHost to clean up the source files could be generalized to something like the code below.  This would reduce the check for wxpo to a single case, keep all the cleanup uniform instead of special cased, and allow for future changes where we handle all combinations of hosts (beyond just this one case).

````
const taskpaneFilePath = "./src/taskpane/taskpane.ts";
let taskpaneContent = await readFileAsync(taskpaneFilePath, "utf8");
let targetHosts = host === "wxpo" ? ["word", "excel", "powerpoint", "outlook"] : [ host]

hosts.forEach(async function (host) {
  if (!targetHosts.contains(host) {
    if (fs.existsSync(`./src/taskpane/${host}.ts`)) {
      await unlinkFileAsync(`./src/taskpane/${host}.ts`);
    }
    taskpaneContent = taskpaneContent.replace(`import "./${host}";`, "");
  }

  if (fs.existsSync(`./manifest.${host}.${manifestType}`)) {
    await unlinkFileAsync(`./manifest.${host}.${manifestType}`);
  }
}

await writeFileAsync(taskpaneFilePath, taskpaneContent);
````
Note that I realized this would leave the single host case with a single import in the taskpane.ts file, but this may help communicate the possibility of being able to handle multiple hosts should the developer try to add one later (putting a comment in the file explaining that would also help).  Ricky should be consulted on this aspect.  If this is really not desired a simple if targetHost.length == 1 with a single file update would be another way to solve this (I think still preferable to looking for host === wxpo).

2024-02-22 21:21 UTC, Rick-Kirkham commented
> I think your code in convertProjectToSingleHost to clean up the source files could be generalized to something like the code below. This would reduce the check for wxpo to a single case, keep all the cleanup uniform instead of special cased, and allow for future changes where we handle all combinations of hosts (beyond just this one case).
> 
> ```
> const taskpaneFilePath = "./src/taskpane/taskpane.ts";
> let taskpaneContent = await readFileAsync(taskpaneFilePath, "utf8");
> let targetHosts = host === "wxpo" ? ["word", "excel", "powerpoint", "outlook"] : [ host]
> 
> hosts.forEach(async function (host) {
>   if (!targetHosts.contains(host) {
>     if (fs.existsSync(`./src/taskpane/${host}.ts`)) {
>       await unlinkFileAsync(`./src/taskpane/${host}.ts`);
>     }
>     taskpaneContent = taskpaneContent.replace(`import "./${host}";`, "");
>   }
> 
>   if (fs.existsSync(`./manifest.${host}.${manifestType}`)) {
>     await unlinkFileAsync(`./manifest.${host}.${manifestType}`);
>   }
> }
> 
> await writeFileAsync(taskpaneFilePath, taskpaneContent);
> ```
> 
> Note that I realized this would leave the single host case with a single import in the taskpane.ts file, but this may help communicate the possibility of being able to handle multiple hosts should the developer try to add one later (putting a comment in the file explaining that would also help). Ricky should be consulted on this aspect. If this is really not desired a simple if targetHost.length == 1 with a single file update would be another way to solve this (I think still preferable to looking for host === wxpo).

I like this code. Let's add comments to the 2 inner conditionals:
// Remove unneeded imports
// Remove unneeded manifest templates

Questions. 
1. Is there some other place in the file where the manifest.{host}.ext files, where `ext` is the manifest type that the user did NOT choose, get deleted?
2. I'm not clear on what the problem is with a single import statement. Why would this not be desired?

2024-02-22 21:57 UTC, millerds commented
> > I think your code in convertProjectToSingleHost to clean up the source files could be generalized to something like the code below. This would reduce the check for wxpo to a single case, keep all the cleanup uniform instead of special cased, and allow for future changes where we handle all combinations of hosts (beyond just this one case).
> > ```
> > const taskpaneFilePath = "./src/taskpane/taskpane.ts";
> > let taskpaneContent = await readFileAsync(taskpaneFilePath, "utf8");
> > let targetHosts = host === "wxpo" ? ["word", "excel", "powerpoint", "outlook"] : [ host]
> > 
> > hosts.forEach(async function (host) {
> >   if (!targetHosts.contains(host) {
> >     if (fs.existsSync(`./src/taskpane/${host}.ts`)) {
> >       await unlinkFileAsync(`./src/taskpane/${host}.ts`);
> >     }
> >     taskpaneContent = taskpaneContent.replace(`import "./${host}";`, "");
> >   }
> > 
> >   if (fs.existsSync(`./manifest.${host}.${manifestType}`)) {
> >     await unlinkFileAsync(`./manifest.${host}.${manifestType}`);
> >   }
> > }
> > 
> > await writeFileAsync(taskpaneFilePath, taskpaneContent);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that I realized this would leave the single host case with a single import in the taskpane.ts file, but this may help communicate the possibility of being able to handle multiple hosts should the developer try to add one later (putting a comment in the file explaining that would also help). Ricky should be consulted on this aspect. If this is really not desired a simple if targetHost.length == 1 with a single file update would be another way to solve this (I think still preferable to looking for host === wxpo).
> 
> I like this code. Let's add comments to the 2 inner conditionals: // Remove unneeded imports // Remove unneeded manifest templates
> 
> Questions.
> 
> 1. Is there some other place in the file where the manifest.{host}.ext files, where `ext` is the manifest type that the user did NOT choose, get deleted?
> 2. I'm not clear on what the problem is with a single import statement. Why would this not be desired?

1. Yes.  The convert to host script takes care of the manifest and content based on what the user asked for and the delete{ext}files takes care of the manifest files the user didn't ask for.
2. With my code the developer who asks for just a single host will have a taskpane.ts file with just a single import statement (nothing else) for {host}.ts with all the code in it for that host.  This might look odd by itself, but would make it easy to add support for another host in another file and maintain a master taskpane.ts file with imports to the departmentalized code.

2024-02-23 02:44 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +  let manifestContent;
Yeah, you make a good point. I will change it. Thanks Darren!

2024-02-23 02:47 UTC, YueLi-MSFT commented on convertToSingleHost.js
> +    content.config["app_to_debug"] = "excel";
Yeah, perhaps I understand your mean that I should put this line `content.config["app_to_debug"] = host;` in the else statement, right?

2024-02-23 04:52 UTC, millerds commented on convertToSingleHost.js
> +    content.config["app_to_debug"] = "excel";
yes

2024-02-23 08:46 UTC, YueLi-MSFT commented
> > > I think your code in convertProjectToSingleHost to clean up the source files could be generalized to something like the code below. This would reduce the check for wxpo to a single case, keep all the cleanup uniform instead of special cased, and allow for future changes where we handle all combinations of hosts (beyond just this one case).
> > > ```
> > > const taskpaneFilePath = "./src/taskpane/taskpane.ts";
> > > let taskpaneContent = await readFileAsync(taskpaneFilePath, "utf8");
> > > let targetHosts = host === "wxpo" ? ["word", "excel", "powerpoint", "outlook"] : [ host]
> > > 
> > > hosts.forEach(async function (host) {
> > >   if (!targetHosts.contains(host) {
> > >     if (fs.existsSync(`./src/taskpane/${host}.ts`)) {
> > >       await unlinkFileAsync(`./src/taskpane/${host}.ts`);
> > >     }
> > >     taskpaneContent = taskpaneContent.replace(`import "./${host}";`, "");
> > >   }
> > > 
> > >   if (fs.existsSync(`./manifest.${host}.${manifestType}`)) {
> > >     await unlinkFileAsync(`./manifest.${host}.${manifestType}`);
> > >   }
> > > }
> > > 
> > > await writeFileAsync(taskpaneFilePath, taskpaneContent);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Note that I realized this would leave the single host case with a single import in the taskpane.ts file, but this may help communicate the possibility of being able to handle multiple hosts should the developer try to add one later (putting a comment in the file explaining that would also help). Ricky should be consulted on this aspect. If this is really not desired a simple if targetHost.length == 1 with a single file update would be another way to solve this (I think still preferable to looking for host === wxpo).
> > 
> > 
> > I like this code. Let's add comments to the 2 inner conditionals: // Remove unneeded imports // Remove unneeded manifest templates
> > Questions.
> > 
> > 1. Is there some other place in the file where the manifest.{host}.ext files, where `ext` is the manifest type that the user did NOT choose, get deleted?
> > 2. I'm not clear on what the problem is with a single import statement. Why would this not be desired?
> 
> 1. Yes.  The convert to host script takes care of the manifest and content based on what the user asked for and the delete{ext}files takes care of the manifest files the user didn't ask for.
> 2. With my code the developer who asks for just a single host will have a taskpane.ts file with just a single import statement (nothing else) for {host}.ts with all the code in it for that host.  This might look odd by itself, but would make it easy to add support for another host in another file and maintain a master taskpane.ts file with imports to the departmentalized code.


I appreciate your feedback on this pull request. I agree with your suggestions, and I will make the necessary modifications accordingly.

2024-02-26 21:11 UTC, millerds approved these changes

2024-02-27 15:51 UTC, merged