Update debug configs and fix one low vulnerabilty
OfficeDev/Office-Addin-TaskPane pull request #89
Opened 2020-11-19 22:33 UTC by TCourtneyOwen

2020-11-19 22:37 UTC, akrantz requested changes

2020-11-19 22:37 UTC, akrantz commented on .vscode/launch.json
> +      "timeout": 60000,
This is only 1 minute for the timeout. I would bump this to 10 minutes by adding another zero.

2020-11-19 22:37 UTC, akrantz commented on .vscode/launch.json
> +      "name": "Office Online (Edge Chromium)",
I think you should also keep the original config using "type": "edge" and call it "Office Online (Edge Legacy)".

2020-11-19 22:38 UTC, TCourtneyOwen commented on .vscode/launch.json
> +      "name": "Office Online (Edge Chromium)",
So keep the original and add the new one as well?

2020-11-19 22:38 UTC, TCourtneyOwen commented on .vscode/launch.json
> +      "timeout": 60000,
sounds good

2020-11-19 22:38 UTC, akrantz commented on .vscode/launch.json
> +      "name": "Office Online (Edge Chromium)",
Actually I take this back. Since this is the browser and Edge Chromium has replaced the legacy versions (unlike with webviews) I don't think you need the other one.

2020-11-19 22:44 UTC, TCourtneyOwen commented on .vscode/launch.json
> +      "name": "Office Online (Edge Chromium)",
OK I will leave the legacy config out

2020-11-20 00:20 UTC, akrantz approved these changes

2020-11-22 17:22 UTC, merged