Content add in
OfficeDev/Office-Addin-TaskPane pull request #95
Opened 2021-01-27 19:24 UTC by arttarawork

2021-01-27 19:27 UTC, TCourtneyOwen commented
Did we get confirmation that PPT and Excel are the only supported hosts?

2021-01-27 19:29 UTC, arttarawork commented
> Did we get confirmation that PPT and Excel are the only supported hosts?

Yup! @keyur32 and @akrantz confirmed.

2021-01-27 19:30 UTC, akrantz requested changes
Please give me time to respond...

2021-01-27 19:31 UTC, akrantz commented
OneNote Online also has support but not OneNote desktop.  Are we going to support that?

2021-01-27 20:47 UTC, akrantz commented on test/src/powerpoint-test-content.ts
> +    return new Promise<void>((resolve, reject) => {
Please change back to use await. Thanks.

2021-01-27 21:59 UTC, TCourtneyOwen commented on manifest.xml
> -  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
We need to add other supported hosts here.  Definitely PPT and maybe Word if it's supported

2021-01-27 21:59 UTC, TCourtneyOwen commented on test/test-manifest.xml
>      <Host Name="Workbook"/>
We need to add PPT and other supported hosts (if any) to the manifest

2021-01-27 21:59 UTC, TCourtneyOwen commented on convertToSingleHost.js
>  const fs = require("fs");
Please incorporate latest changes to convertToSingleHost that were just added at https://github.com/OfficeDev/Office-Addin-TaskPane/commit/57709ce2558d4777243f7d22d60b7ac420ec49d8#diff-d66dc199c22efc5aae8a395f81d475b407fbfcb23f843903241caaf6f373ebe7

2021-01-27 23:59 UTC, akrantz commented on test/src/powerpoint-test-content.ts
> +    return new Promise<void>(async (resolve, reject) => {
Also this code shouldn't use `new Promise()` with resolve() and reject(). An async function resolves when it reaches the end and rejects by throwing an exception.

2021-01-27 23:59 UTC, akrantz commented on test/src/powerpoint-test-content.ts
> +    return new Promise<void>(async (resolve, reject) => {
You can remove the try/catch and just allow the exception to propogate.

2021-01-28 00:05 UTC, arttarawork commented on test/src/powerpoint-test-content.ts
> +            await run();
Weird behavior with getSelectedDataAsync(). Running run() once adds "Hello World!" to the slide, but doesn't select the new text properly, so running getSelectedDataAsync() after running run() once returns "". Running run() twice inserts "Hello World! Hello World!". At this point, the latter part (" Hello World!") is what's selected, which is what getSelectedDataAsync() reads. 

It's a workaround I don't like, so if there's a proper way to select that text, I would use it, but I haven't found anything that lets me do that.

2021-01-28 00:49 UTC, arttarawork commented on test/src/powerpoint-test-content.ts
> +    return new Promise<void>(async (resolve, reject) => {
Let me know if the recent changes are satisfactory for that

2021-01-28 17:10 UTC, TCourtneyOwen commented
/AzurePipelines run

2021-01-28 18:08 UTC, arttarawork commented
/AzurePipelines run

2021-02-03 04:49 UTC, akrantz commented on src/content/powerpoint.ts
> +}
need a newline at the end of the last line...

2021-02-04 13:07 UTC, akrantz commented
See https://github.com/OfficeDev/Office-Addin-Content/pull/1

2021-02-04 13:07 UTC, closed without merging

2021-02-04 17:13 UTC, TCourtneyOwen commented
@Artur, do you want to try moving this branch over to https://github.com/OfficeDev/Office-Addin-Content so we can then see if it passes the CI job?

2021-02-04 17:16 UTC, arttarawork commented
> @artur, do you want to try moving this branch over to https://github.com/OfficeDev/Office-Addin-Content so we can then see if it passes the CI job?

The contents of this branch should be already included in this PR: https://github.com/OfficeDev/Office-Addin-Content/pull/1

@akrantz are we good to merge that PR?

2021-02-04 17:17 UTC, TCourtneyOwen commented
One thing I would check out is that linting passes. I noticed in a trial run of the CI pipeline against the commit that Adam made to populate the new repo that the linting phase failed in the CI job

2021-02-04 17:21 UTC, akrantz commented
This branch is already part of https://github.com/OfficeDev/Office-Addin-Content/pull/1. Let's comment about any remaining work like fixing linting issues there.

2021-02-04 17:22 UTC, arttarawork commented
> One thing I would check out is that linting passes. I noticed in a trial run of the CI pipeline against the commit that Adam made to populate the new repo that the linting phase failed in the CI job

True, but the first PR in that branch is supposed to be the actual content add-in. Is there a way to set up pipelines for PRs? I think I can manually run the pipeline for now from the ADO menu

2021-02-04 17:23 UTC, arttarawork commented
^ https://office.visualstudio.com/OC/_build/results?buildId=7252873&view=results

2021-02-04 17:26 UTC, TCourtneyOwen commented
The pipeline is hooked up already.  As long as your PR is against main it will run