Adding PowerPoint Test for Taskpane
OfficeDev/Office-Addin-TaskPane pull request #97
Opened 2021-01-28 23:29 UTC by arttarawork

There is also a small change to the test runner to only shut off the test server once the very last host has been tested. Otherwise, there's an issue where the dev server closes and doesn't reopen before the next host gets tested. This issue hasn't been encountered before, since it's only a problem if the previous host wasn't Excel. We only previously tested Excel and Word (in that order), so this includes a small change to accommodate that issue for including another host.

2021-01-28 23:39 UTC, akrantz requested changes
Please see the comments.

2021-01-28 23:39 UTC, akrantz commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
only need one line that has `await run();`

2021-01-28 23:39 UTC, akrantz commented on test/src/test-taskpane.ts
> +import "./word-test-taskpane";
please put in alphabetic order

2021-01-28 23:39 UTC, akrantz commented on test/ui-test.ts
> +const hosts = ["Excel", "Word", "PowerPoint"];
Please put in alphabetic order.

2021-01-28 23:39 UTC, akrantz commented on test/ui-test.ts
> +            if (host == hosts[hosts.length - 1]) {
Why are you adding this check that there is only one host? This shouldn't be required as far as I am aware.

2021-01-28 23:39 UTC, akrantz commented on test/ui-test.ts
> +            if (host == hosts[hosts.length - 1]) {
Really I think you are pointing out that this could be optimized to start the dev server once, then run the test for each host (which includes startDebugging() and stopDebugging()), and then it can do after(). I don't think you should need to change this here because it is beyond the task of adding the powerpoint support.

2021-01-28 23:41 UTC, arttarawork commented on test/ui-test.ts
> +            if (host == hosts[hosts.length - 1]) {
Without this change, whatever tests following a non-Excel host will fail. I can change the tests so we start/end the dev server in the before/after, though.

2021-01-28 23:41 UTC, akrantz commented on test/ui-test.ts
> +            if (host == hosts[hosts.length - 1]) {
The problem with the dev server that you mentioned would require fixing this to start the dev server once before the loop for each host, and then stopping it afterwards. I guess you should go ahead and make this change.

2021-01-28 23:42 UTC, arttarawork commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
https://github.com/OfficeDev/Office-Addin-TaskPane/pull/95#discussion_r565726957

2021-01-28 23:42 UTC, arttarawork commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
"Weird behavior with getSelectedDataAsync(). Running run() once adds "Hello World!" to the slide, but doesn't select the new text properly, so running getSelectedDataAsync() after running run() once returns "". Running run() twice inserts "Hello World! Hello World!". At this point, the latter part (" Hello World!") is what's selected, which is what getSelectedDataAsync() reads.

It's a workaround I don't like, so if there's a proper way to select that text, I would use it, but I haven't found anything that lets me do that."

2021-01-28 23:45 UTC, akrantz commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
@wandyezj Could you help see if there a way to update the test code here so it has the selected text? It would help to understand if this highlights a bug with PowerPoint, a timing problem, or something else.

2021-01-29 22:45 UTC, akrantz commented on test/ui-test.ts
> +after(`Unregister the add-in`, callback => {
Do you not like using async/await code? 

I have this vague recollection that we use function() { } for the callback rather than arrow notation () => { } because the latter has some issue with mocha.

```
after("Unregister the add-in", async function(callback) => {
  await stopDebugging(manifestPath);
  setImmediate(callback);
}
```

2021-01-29 23:01 UTC, arttarawork commented on test/ui-test.ts
> +after(`Unregister the add-in`, callback => {
Gotcha, no I actually prefer the code I had in its place earlier, with just the stopDebugging.

This is mostly because there's a weird issue where the tests are failing on Mac but not on windows. 

I figured maybe this would fix it? https://github.com/sindresorhus/gulp-mocha/issues/129

But it clearly didn't, based off the latest pipeline run.

2021-01-29 23:17 UTC, TCourtneyOwen commented on test/ui-test.ts
> +            if (host == hosts[hosts.length - 1]) {
I think you are still start and stopping the dev-server multiple times here, which can lead to test unreliability.  It's something we should have fixed long ago.  You can see an example for how I am doing in this another branch at https://github.com/TCourtneyOwen/Office-Addin-TaskPane/blob/add-web-tests/test/ui-tests.ts

2021-02-01 21:14 UTC, akrantz commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
@TCourtneyOwen How do you feel about this redundant `await run()` as a workaround for this issue? Is there some way to avoid the issue? I feel like it would be better to only have a single run() if possible and would like to understand better the reason for the issue. Should we change the test code to something else to avoid it?

2021-02-01 21:15 UTC, akrantz commented on test/src/test-helpers.ts
> +            processName = (process.platform === "win32") ? "Powerpnt" : "PowerPoint";
Are all non-win32 platforms "Powerpnt"? Seems like it would be better to use a switch statement with "Powerpoint" as the default case, and the specific platforms called out which need the alternate spelling.

2021-02-01 21:22 UTC, TCourtneyOwen commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
Can't we use setSelectedDataAsync to set the text:  https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=powerpoint-js-1.1#setSelectedDataAsync_data__callback_

2021-02-01 21:26 UTC, arttarawork commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
The run function in `src\taskpane\powerpoint.ts` is already using setSelectedDataAsync:
```
export async function run() {
  /**
   * Insert your PowerPoint code here
   */
  Office.context.document.setSelectedDataAsync(
    "Hello World!",
    {
      coercionType: Office.CoercionType.Text
    },
    result => {
      if (result.status === Office.AsyncResultStatus.Failed) {
        console.error(result.error.message);
      }
    }
  );
}
```

2021-02-01 21:50 UTC, wandyezj commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
How come the setSelectedDataAsync is not awaited?

2021-02-01 21:59 UTC, arttarawork commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
I can put an await on `setSelectedDataAsync`, but the same issue remains. I'll push out a change with the await, if requested, though.

2021-02-02 00:26 UTC, TCourtneyOwen commented on test/ui-test.ts
>                  assert.equal(applicationClosed, true);
Can you please change assert.equal to assert.strictEqual throughout

2021-02-02 19:25 UTC, akrantz commented on src/taskpane/powerpoint.ts
> +  return new Promise<void>((resolve, reject) => {
We prefer to use async/await where feasible. This looks to do the same thing as before except where the `reject(result.error)` is which should be `throw result.error` (instead of `console.error()`) in the original async code. Is that really the fix?

2021-02-02 19:26 UTC, akrantz commented on test/src/powerpoint-test-taskpane.ts
> +    await new Promise<void>((resolve, reject) => {
this is doing the same thing as the redundant `run()`. This isn't any better.

2021-02-02 19:27 UTC, akrantz commented on test/src/powerpoint-test-taskpane.ts
> +    await actualTest();
I am confused why this was added. We want to test the `run()` method of the original code. Adding the actualTest() function doesn't help with that.

2021-02-02 19:29 UTC, arttarawork commented on test/src/powerpoint-test-taskpane.ts
> +    await actualTest();
The actualTest method puts the code that reads the result separately for readability. I can add it back to runTest if needed.

2021-02-02 22:46 UTC, akrantz commented on test/src/powerpoint-test-taskpane.ts
> +    await run();
This has now been addressed.

2021-02-02 22:47 UTC, arttarawork commented on test/ui-test.ts
>                  assert.equal(applicationClosed, true);
Done!

2021-02-02 22:48 UTC, arttarawork commented on test/src/test-helpers.ts
> +            processName = (process.platform === "win32") ? "Powerpnt" : "PowerPoint";
Win32 uses Powerpnt, while Mac uses PowerPoint. I don't think we run on any other native operating systems.

2021-02-02 22:50 UTC, akrantz commented on test/src/test-helpers.ts
> +            processName = (process.platform === "win32") ? "Powerpnt" : "PowerPoint";
ok fine.

2021-02-02 22:50 UTC, akrantz approved these changes

2021-02-02 22:51 UTC, merged